services:
  # ============================================
  # PostGreSQL Database
  # ============================================
  # postgres-db:
  #   image: postgres:18.3-bookworm
  #   container_name: inferno-db
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "${DB_PORT}:5432"
  #   volumes:
  #     - type: volume
  #       source: inferno-data
  #       target: /var/lib/postgresql/data
  #     # - type: bind
  #     #   source: ./init.sql        
  #     #   target: /docker-entrypoint-initdb.d/init.sql
  #     #   read_only: true
  #   restart: unless-stopped

  # ============================================
  # C++ Shared library (Development)
  # ============================================
  shared:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: inferno-shared
    volumes:
      - type: bind
        source: ./shared
        target: /app/shared
      - type: bind
        source: ./inferno.sh
        target: /app/inferno.sh
      - type: volume
        source: shared-build
        target: /app/shared/build
    command: ["bash", "./inferno.sh", "test", "shared"]

  # ============================================
  # C++ Server (Development / Builder)
  # ============================================
  server-builder:
    depends_on:
    #   - inferno-db
      shared:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: inferno-server
    volumes:
      - type: bind
        source: ./server
        target: /app/server
      - type: bind
        source: ./shared
        target: /app/shared
      - type: bind
        source: ./inferno.sh
        target: /app/inferno.sh
      - type: volume
        source: shared-build
        target: /app/shared/build
      - type: volume
        source: server-build
        target: /app/server/build
    command: ["bash", "./inferno.sh", "test", "server"]

  # ============================================
  # C++ Server (Development)
  # ============================================
  server:
    depends_on:
      server-builder:
        condition: service_completed_successfully
    #   - inferno-db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: inferno-db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - type: volume
        source: server-build
        target: /app/server/build
    command: ["./server/build/bin/server"]


  # ============================================
  # C++ Agent (Development / Builder)
  # ============================================
  agent-builder:
    depends_on:
      shared:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./agent
        target: /app/agent
      - type: bind
        source: ./shared
        target: /app/shared
      - type: bind
        source: ./inferno.sh
        target: /app/inferno.sh
      - type: volume
        source: shared-build
        target: /app/shared/build
      - type: volume
        source: agent-build
        target: /app/agent/build
    command: ["bash", "./inferno.sh", "test", "agent"]


  # ============================================
  # C++ Agent (Runtime/Deployment)
  # ============================================
  agent:
    depends_on:
      agent-builder:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Server configuration
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - type: volume
        source: agent-build
        target: /app/agent/build
    command: ["./agent/build/bin/agent"]

volumes:
  # inferno-data:
  shared-build:
  server-build:
  agent-build: